version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
